data-bridge:
  file-regex: ${FILE_REGEX:(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})_(?<hour>[0-9]{2})(?<minute>[0-9]{2})_.*.(uct|UCT)}
  sources:
    minio:
      url: ${SOURCE_MINIO_URL:http://localhost:9000}
      access-key: ${SOURCE_MINIO_ACCESS_KEY:gridcapa}
      secret-key: ${SOURCE_MINIO_SECRET_KEY:gridcapa}
      bucket: ${SOURCE_MINIO_INPUTS_BUCKET:gridcapa}
      base-directory: ${SOURCE_MINIO_BASE_DIRECTORY:outputs}
      polling-delay-in-ms: 10000
  sinks:
    ftp:
      active: ${SINK_FTP_ACTIVE:false}
      host: ${SINK_FTP_HOST:localhost}
      port: ${SINK_FTP_PORT:21}
      username: ${SINK_FTP_USERNAME:gridcapa}
      password: ${SINK_FTP_PASSWORD:gridcapa}
      base-directory: ${SINK_FTP_BASE_DIRECTORY:/data/gridcapa/cse/d2cc/outputs}
    sftp:
      active: ${SINK_SFTP_ACTIVE:false}
      host: ${SINK_SFTP_HOST:localhost}
      port: ${SINK_SFTP_PORT:2222}
      username: ${SINK_SFTP_USERNAME:gridcapa}
      password: ${SINK_SFTP_PASSWORD:gridcapa}
      base-directory: ${SINK_SFTP_BASE_DIRECTORY:/data/core/valid/outputs}



