name: Release job

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: true
      nextVersion:
        description: 'Next version'
        required: true
      mergeAutomatically:
        description: 'Merges version commit automatically'
        required: true
        type: boolean
        default: "false"

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change Maven version to release version
        run: mvn --batch-mode versions:set -DnewVersion=${{ github.event.inputs.releaseVersion }}

      - name: Commit release version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: release-v${{ github.event.inputs.releaseVersion }}
          create_branch: true
          commit_message: Prepare release ${{ github.event.inputs.releaseVersion }}

      - name: Build with Maven
        run: mvn --batch-mode -Pdefault,coverage install

      - name: Run SonarCloud analysis
        run: >
          mvn --batch-mode -DskipTests sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=farao-community
          -Dsonar.projectKey=farao-community_gridcapa-output-data-bridge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Generate release tag
        run: git tag -a v${{ github.event.inputs.releaseVersion }} "Release version v${{ github.event.inputs.releaseVersion }}"

      - name: Build and publish Docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: farao/gridcapa-output-data-bridge
          username: farao
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: v${{ github.event.inputs.releaseVersion }}

      - name: Change Maven version to next version
        run: mvn --batch-mode versions:set -DnewVersion=${{ github.event.inputs.nextVersion }}-SNAPSHOT

      - name: Commit next version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: release-v${{ github.event.inputs.releaseVersion }}
          commit_message: Prepare next release ${{ github.event.inputs.nextVersion }}

      - name: Merge automatically
        if: ${{ github.event.inputs.mergeAutomatically }}
        run: echo 'Merge automatically cause value is ${{ github.event.inputs.mergeAutomatically }}'
